spring:
  datasource:
    url: jdbc:mysql://localhost:3310/directorio
    username: root
    password: kupita
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true